spring.application.name=elms-backend
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# Database
spring.datasource.url=jdbc:mysql://10.199.100.45:3307/elms
spring.datasource.username=root
spring.datasource.password=polus123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always